### ISSUE TITLE
Compile RoCE module problem

### ISSUE THREAD

**Issue by dongzhangqi7** [shsym/mind#3]
When I compile RoCE module, **insmod roce4disagg.ko** meet a error as follows:
**insmod: ERROR: could not insert module roce4disagg.ko: Invalid module format.**
My environment is following README as Ubuntu 18.04 Linux 4.15.0-213-generic
MLNX_OFED_LINUX-5.0-1.0.0.0-ubuntu18.04-x86_64 

Do you have any suggestions? Thank you very much.

**Comment by shsym** [comment]
We tested it with v4.15.0-109 and it can be because of subtle API changes between versions.
Please also ensure that you have the corresponding ofa kernel placed accordingly to the Makefile ([location 1](https://github.com/Yale-NeRD/mind/blob/00802e129c79be09d75fe3ff368cc95a38c8de9e/mind_linux/roce_modules/Makefile#L1), [location 2](https://github.com/Yale-NeRD/mind/blob/00802e129c79be09d75fe3ff368cc95a38c8de9e/mind_linux/roce_modules/Makefile#L23), etc.)

**Comment by shsym** [comment]
Closed as it has not been active for 2 weeks. Please reopen the issue if the problem persists.
